In [ ]:
import numpy as np

In [ ]:
# Extraindo amostras
X_train = np.array([[1], [2], [3], [4], [5]])
y_train = np.array([i[0] ** 2 for i in X_train])
X_test = np.array([[1], [2], [3], [4], [5]])
y_test = np.array([i[0] ** 2 for i in X_test])

In [ ]:
class PolynomialRegression:

    '''
    Docstring
    '''

    def __init__(self, degree, alpha = 0.01, n_iters = 1000):
        self.degree = degree
        self.alpha = alpha
        self.n_iters = n_iters

    def fit(self, X, y):
        m = X.shape[0]

        # Eleva cada feature aos graus contidos no range
        # O '+1' em self.degree é porque o range vai de 1 a self.degree - 1
        # Colunas de 1
        X_poly = np.hstack([X ** i for i in range(0, self.degree + 1)])

        print(X_poly)
        # Vetor com a quantidade de zeros igual ao número de colunas de X_poly
        print(X_poly.shape)
        self.w_ = np.zeros(self.degree + 1)
        self.b_ = 0

        # 'np.dot(A, B)' é o mesmo que 'A @ B'
        #  O _ evita que uma variável seja criada na memória
        for _ in range(self.n_iters):

            dJdw = np.dot(X_poly.T, ((np.dot(X_poly, self.w_) + self.b_) - y))
            dJdb = (np.dot(X_poly, self.w_) + self.b_) - y

            # Atualização simultânea dos parâmetros
            self.w_ = self.w_ - (1/m) * self.alpha * dJdw
            print(self.w_)
            self.b_ = self.b_ - (1/m) * self.alpha * dJdb
            print(self.b_)

    def predict(self, X):
        X_poly = np.hstack([X ** i for i in range(0, self.degree + 1)])
        y_pred = np.dot(self.w_, X_poly) + self.b_
        return y_pred

In [ ]:
model = PolynomialRegression(degree = 3, alpha = 0.03, n_iters = 100)
model.fit(X_train, y_train)

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
(5, 4)
[ 0.33   1.35   5.874 26.55 ]
[0.006 0.024 0.054 0.096 0.15 ]
[  -37.2543   -161.6679   -729.62502 -3379.4289 ]
[ -0.19266  -1.3857   -4.5369  -10.60206 -20.53698]
[  4781.9722374  20733.114537   93520.8269766 433012.775805 ]
[  25.66235268  180.53374248  585.54510228 1361.40580728 2628.82523268]
[  -612684.9493105   -2656432.40094578 -11982432.71473185
 -55480321.25822685]
[  -3286.77775877  -23127.12775392  -75017.99640057 -174427.85850875
 -336825.18888849]
[7.85010874e+07 3.40358963e+08 1.53526518e+09 7.10848993e+09]
[  421124.17684707  2963198.76306827  9611787.46891899 22348806.19573423
 43156170.844849  ]
[-1.00580562e+10 -4.36089446e+10 -1.96707892e+11 -9.10784722e+11]
[-5.39570935e+07 -3.79663775e+08 -1.23152304e+09 -2.86347050e+09
 -5.52944176e+09]
[1.28870182e+12 5.58745399e+12 2.52034601e+13 1.16695503e+14]
[6.91332433e+09 4.86449259e+10 1.57790526e+11 3.66885964e+11
 7.08